### ISSUE TITLE
Internet Explorer 8 Support

### ISSUE THREAD

**Issue by CIRCA100** [slightlyoffbeat/brew#37]
This theme is nice, but I think it is is broken in IE8. 

Any chance of making it compatible?

**Comment by slightlyoffbeat** [comment]
What is broken?  Any screenshots?

**Comment by msacchetti** [comment]
Basically without adding respond.js the site only shows mobile view in IE8.

**Comment by anagio** [comment]
Yes if you use the program IETester and view your demo in IE8 it's forcing the responsive layout. However when viewing bootstraps website in IE8 with IETester it renders perfectly fine. Here is a screen shot. This should really be fixed soon since bootstrap itself supports IE8.

![ie8brew](https://cloud.githubusercontent.com/assets/1071553/4876531/4b065100-62c9-11e4-8649-9eaf8d39248c.jpg)

**Comment by anagio** [comment]
I'll likely fix this and submit a pull request this week or over the weekend.
